# Generated by Django 5.1.8 on 2025-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_schema',
            fields=[
                ('question_number', models.AutoField(primary_key=True, serialize=False)),
                ('question_num', models.PositiveSmallIntegerField()),
                ('question_text', models.CharField(max_length=200)),
                ('yes_answer_text', models.CharField(blank=True, max_length=200)),
                ('no_answer_text', models.CharField(blank=True, max_length=200)),
                ('yes_answer', models.PositiveSmallIntegerField()),
                ('no_answer', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
